#ifndef GLOBAL_VARIABLES_H
#define GLOBAL_VARIABLES_H

#include <stdint.h>

extern pointer switchdataD_0040271d;
extern pointer ascii_manager_big_child_on_tick_A_jump_table;
extern pointer switchdataD_0040303e;
extern pointer ascii_manager_big_child_on_tick_B_jump_table;
extern pointer switchdataD_004040ac;
extern pointer std_jump_table;
extern pointer switchdataD_0040a9a4;
extern pointer ecl_jump_table;
extern pointer sub_0x40a9b0;
extern pointer sub_0x40a9b4;
extern pointer sub_0x40a9d4;
extern pointer sub_0x40a9d8;
extern pointer sub_0x40a9dc;
extern pointer sub_0x40a9e0;
extern pointer sub_0x40a9e4;
extern pointer sub_0x40a9f0;
extern pointer sub_0x40a9f4;
extern pointer sub_0x40a9f8;
extern pointer sub_0x40a9fc;
extern pointer sub_0x40aa00;
extern pointer sub_0x40aaac;
extern pointer sub_0x40aab0;
extern pointer sub_0x40aab4;
extern pointer sub_0x40aab8;
extern pointer sub_0x40aabc;
extern pointer sub_0x40aac0;
extern pointer sub_0x40aac4;
extern pointer sub_0x40aac8;
extern pointer sub_0x40aacc;
extern pointer sub_0x40aaf4;
extern pointer sub_0x40aaf8;
extern pointer switchdataD_0040abc0;
extern pointer move_interp_modes_jump_table;
extern pointer switchdataD_0040b31c;
extern pointer eclvar_jump_table;
extern pointer switchdataD_0040f3ac;
extern pointer stage_eff_anm_jump_table;
extern pointer switchdataD_0040f7a4;
extern pointer [switch]Ending::__sub_40F550_jump_table;
extern pointer switchdataD_004105e3;
extern pointer end_type_jump_table;
extern uint8_t[65] lookup_table_4105ef;
extern uint8_t[65] end_type_case_table;
extern pointer switchdataD_00410630;
extern pointer end_ins_jump_table;
extern uint8_t[75] lookup_table_410678;
extern uint8_t[75] end_ins_case_table;
extern pointer switchdataD_00411d63;
extern pointer timeline_ins_jump_table;
extern pointer switchdataD_00412e3f;
extern pointer [switch]EnemyManager::on_tick_jump_table;
extern pointer switchdataD_0041413b;
extern pointer BulletAimModes_JumpTable;
extern pointer switchdataD_004164e0;
extern pointer BulletState_JumpTable;
extern pointer switchdataD_00416c3a;
extern pointer [switch]__sub_416B50_jump_table;
extern pointer switchdataD_00416d44;
extern pointer [switch]__sub_416C50_jump_table;
extern pointer switchdataD_004190b4;
extern pointer msg_jump_table;
extern pointer switchdataD_0041caad;
extern pointer [switch]UpdateFuncRegistry::run_all_on_tick_jump_table;
extern pointer switchdataD_0041cb6e;
extern pointer [switch]UpdateFuncRegistry::run_all_on_draw_jump_table;
extern pointer switchdataD_004200f8;
extern pointer item_jump_table;
extern pointer switchdataD_00420114;
extern pointer item_point_value_jump_table;
extern pointer switchdataD_004230ff;
extern pointer [switchA]UnknownB::__sub_422900_jump_table;
extern uint8_t[113] switchdataD_0042310f;
extern uint8_t[113] lookup_table_42310f;
extern uint8_t[113] [switchA]UnknownB::__sub_422900_case_table;
extern pointer switchdataD_00423180;
extern pointer [switchB]UnknownB::__sub_422900_jump_table;
extern uint8_t[65] lookup_table_423194;
extern uint8_t[65] [switchB]UnknownB::__sub_422900_case_table;
extern pointer switchdataD_004231d5;
extern pointer [switchC]UnknownB::__sub_422900_jump_table;
extern uint8_t[94] lookup_table_4231f5;
extern uint8_t[94] [switchC]UnknownB::__sub_422900_case_table;
extern pointer switchdataD_00426c2d;
extern pointer [switch]Player::__sub_4264B0_jump_table;
extern pointer switchdataD_004285fa;
extern pointer [switchA]Player::__sub_427860_jump_table;
extern pointer switchdataD_0042861a;
extern pointer [switchB]Player::__sub_427860_jump_table;
extern pointer switchdataD_00434a63;
extern pointer anm_jump_table;
extern pointer switchdataD_004374d0;
extern pointer [switchA]Menu::on_tick_jump_table;
extern pointer switchdataD_00437518;
extern pointer [switchB]Menu::on_tick_jump_table;
extern pointer switchdataD_004381cc;
extern pointer [switch]Menu::__sub_437B41_jump_table;
extern pointer switchdataD_0043bbe0;
extern pointer [switch]CWaveFile__sub_43BA60_jump_table;
extern pointer switchdataD_0043c370;
extern pointer switchdataD_0043f342;
extern pointer [switch]__sub_43F245_jump_table;
extern pointer switchdataD_004432f2;
extern pointer switchdataD_00449cae;
extern pointer switchdataD_0045093d;
extern pointer switchdataD_0045810d;
extern pointer switchdataD_0045917d;
extern pointer switchdataD_0045ccf4;
extern pointer switchdataD_0045cd70;
extern pointer switchdataD_0045cddc;
extern pointer switchdataD_0045ce80;
extern pointer switchdataD_0045cf0c;
extern pointer switchdataD_0045cf78;
extern pointer switchdataD_0045d034;
extern pointer switchdataD_0045d0b0;
extern pointer switchdataD_0045d11c;
extern pointer switchdataD_0045d1c0;
extern pointer switchdataD_0045d24c;
extern pointer switchdataD_0045d2b8;
extern pointer switchdataD_0045f26a;
extern pointer switchdataD_00468486;
extern string "data/capture.anm";
extern string "data/asciis.anm";
extern string "data/ascii.anm";
extern string "data/stg7bg.anm";
extern string "data/stage6.std";
extern string "data/stg6bg.anm";
extern string "data/stage5.std";
extern string "data/stg5bg.anm";
extern string "data/stage4.std";
extern string "data/stg4bg.anm";
extern string "data/stage3.std";
extern string "data/stg3bg.anm";
extern string "data/stage2.std";
extern string "data/stg2bg.anm";
extern string "data/stage1.std";
extern string "data/stg1bg.anm";
extern string spriteAnimDummy;
extern string "dummy";
extern string [SJIS]"Spiritual_sign_"dream_seal"";
extern string [SJIS]"Dream_mark_"sealing_demons"";
extern string [SJIS]"Magic_mark_"Stardust_Reverie"";
extern string [SJIS]"Love_sign_"Master_Spark"";
extern string [SJIS]"Failed_to_read_enemy_data,_data_is_corrupted_or_lost\n";
extern string "error_:_sub_anim_overflow\n";
extern string "error_:_no_Stack_Ret\n";
extern float Pi/6_f;
extern float 30.0f;
extern float Pi/3_f;
extern float 0.1f;
extern float Pi/4_f;
extern float Pi*3/4_f;
extern float 128.0f;
extern float [10?]r_f;
extern float 9.0f;
extern float 120.0f;
extern float 4/15_f;
extern float 20.0f;
extern float -Pi/4_f;
extern float 40.0f;
extern float 160.0f;
extern float Pi/180_f;
extern float -Pi*7/8_f;
extern float 256.0f;
extern float 224.0f;
extern float 192.0f;
extern float 2.2f;
extern float 320.0f;
extern float 6000.0f;
extern float 19.0f;
extern float 12.0f;
extern float 33.0f;
extern float 4.0f;
extern float 255.0f;
extern float 0.00001f;
extern float 240.0f;
extern string "data/eff05.anm";
extern string "data/eff04.anm";
extern string "data/eff03.anm";
extern string "data/eff02.anm";
extern string "data/eff01.anm";
extern string [SJIS]"error_:_The_ending_file_cannot_be_read,_the_file_is_corrupted\n";
extern string "data/end11.end";
extern string "data/end10.end";
extern string "data/end01.end";
extern string "data/end00.end";
extern string "data/end10b.end";
extern string "data/end00b.end";
extern string "data/staff03.anm";
extern string "data/staff02.anm";
extern string "data/staff01.anm";
extern string [SJIS]"KoumakyoED.dat";
extern float -990.0f;
extern float 1.5f;
extern float -999.0f;
extern float -1.0f;
extern float 640.0f;
extern float 448.0f;
extern float 384.0f;
extern float 5.0f;
extern float 2.5f;
extern string "data/etama4.anm";
extern string "data/etama3.anm";
extern float 416.0f;
extern float 232.0f;
extern pointer g_+%d;
extern pointer "+%d";
extern string "Spell_Card_Bonus!";
extern float 80.0f;
extern float 17.0f;
extern string "Full_Power_Mode!!";
extern string "BONUS_%8d";
extern string "Total_____=_%8d";
extern string "Player_Penalty_*_0.2\n";
extern string "Player_Penalty_*_0.5\n";
extern string "Extra_Rank_____*_2.0\n";
extern string "Lunatic_Rank___*_1.5\n";
extern string "Hard_Rank______*_1.2\n";
extern string "Normal_Rank____*_1.0\n";
extern string "Easy_Rank______*_0.5\n";
extern string "Bomb______=_%8d\n";
extern string "Player____=_%8d\n";
extern string "____*_Point_Item_%3d\n";
extern string "Graze_*___10_=_%5d\n";
extern string "Power_*__100_=_%5d\n";
extern string "Stage_*_1000_=_%5d\n";
extern string "All_Clear!\n\n";
extern string "Stage_Clear\n\n";
extern float 74.0f;
extern string [SJIS]"ô%s";
extern string "data/msg7.dat";
extern string "data/face12b.anm";
extern string "data/face12a.anm";
extern string "data/msg6.dat";
extern string "data/face10b.anm";
extern string "data/face10a.anm";
extern string "data/msg5.dat";
extern string "data/face09b.anm";
extern string "data/face09a.anm";
extern string "data/msg4.dat";
extern string "data/face08b.anm";
extern string "data/face08a.anm";
extern string "data/msg3.dat";
extern string "data/face06b.anm";
extern string "data/face06a.anm";
extern string "data/msg2.dat";
extern string "data/face05a.anm";
extern string "data/msg1.dat";
extern string "data/face03b.anm";
extern string "data/face03a.anm";
extern string "data/face01c.anm";
extern string "data/face01b.anm";
extern string "data/face01a.anm";
extern string "data/face00c.anm";
extern string "data/face00b.anm";
extern string "data/face00a.anm";
extern string "data/loading.anm";
extern string "data/front.anm";
extern string [SJIS]"error_:_Could_not_read_message_file_%s\n";
extern string "data/face12c.anm";
extern string "data/eff07.anm";
extern string "data/eff06.anm";
extern float 104.0f;
extern float -312.0f;
extern float 0.02f;
extern float 0.01f;
extern string g_%.9d;
extern string "%.9d";
extern float 202.0f;
extern float 488.0f;
extern float 226.0f;
extern float 206.0f;
extern float 186.0f;
extern float 146.0f;
extern float 122.0f;
extern float 82.0f;
extern float 58.0f;
extern float 496.0f;
extern float 624.0f;
extern float 0.49f;
extern float 464.0f;
extern string "%.2d";
extern string g_%d;
extern string "%d";
extern float 24.0f;
extern float 288.0f;
extern float -128.0f;
extern float 15.0f;
extern string "DEMO_PLAY";
extern string g_extraStageStr;
extern string "EXTRA_STAGE";
extern string g_finalStageStr;
extern string "FINAL_STAGE";
extern float 136.0f;
extern string "STAGE_%d";
extern float 198.0f;
extern float 168.0f;
extern string data/ecldata7.ecl;
extern string data/ecldata6.ecl;
extern string data/ecldata5.ecl;
extern string data/ecldata4.ecl;
extern string data/ecldata3.ecl;
extern string data/ecldata2.ecl;
extern string data/ecldata1.ecl;
extern string data/stg7enm2.amn;
extern string data/stg7enm.amn;
extern string data/stg6enm2.amn;
extern string data/stg6enm.amn;
extern string data/stg5enm2.amn;
extern string data/stg5enm.amn;
extern string data/stg4enm.anm;
extern string data/stg3enm.amn;
extern string data/stg2enm2.amn;
extern string data/stg2enm.amn;
extern string data/stg1enm2.anm;
extern string data/stg1enm.amn;
extern string demo_replay_file;
extern string [SJIS]"error_:_Failed_to_initialize_2D_display\n";
extern string [SJIS]"error_:_Effect_initialization_failed\n";
extern string [SJIS]"error_:_Failed_to_initialize_the_enemy_brain\n";
extern string [SJIS]"error_:_Failed_to_initialize_the_enemy\n";
extern string [SJIS]"error_:_Failed_to_initialize_enemy_bullets\n";
extern string "data/etama.anm";
extern string [SJIS]"error_:_Failed_to_initialize_player\n";
extern string [SJIS]"error_:_Failed_to_initialize_background_data\n";
extern string [SJIS]"KoumakyoST.dat";
extern string [SJIS]"KoumakyoCM.dat";
extern string "score.dat";
extern float 368.0f;
extern float 100.0f;
extern float 10000.0f;
extern void *[3] VTABLE_46afac;
extern void *[3] __UnknownB_FuncPtr;
extern string "add_calc_chain_[pri_=_%d]\n";
extern string "add_draw_chain_[pri_=_%d]\n";
extern string "draw_out_Chain_[Pri_=_%d]\n";
extern string "calc_out_Chain_[Pri_=_%d]\n";
extern string [SJIS]"There_doesn't_seem_to_be_a_usable_pad,_sorry\n";
extern string "error_:_DIERR_INPUTLOST_%d\n";
extern string "error_:_DIERR_INPUTLOST\n";
extern string "D3DXCreateFontIndirect_FALSE";
extern LPCSTR lpCaption_0046b0a8;
extern LPCSTR "ok";
extern string g_pszFaceName;
extern string g_fontFaceName;
extern string [SJIS]"MS_gothic";
extern string "error_:_%s_is_not_found.\n";
extern string MODE_RB_LOGGING;
extern string "%s_Load_..._\n";
extern string "%s_Decode_..._\n";
extern string "wb";
extern string [SJIS]"Touhou_motion_record_---------------------------------------------_\n";
extern float 2^32_f;
extern float 0.03f;
extern float -2.2f;
extern float -8.0f;
extern string [SJIS]"The_option_that_requires_a_reboot_has_changed,_so_reboot\n";
extern string config_file;
extern double 0.6d;
extern double 0.865d;
extern double 1000.0d;
extern double 2.0d;
extern double 60.0d;
extern double 16_2/3_d;
extern string [SJIS]"Direct3D_object_could_not_be_created_for_some_reason\n";
extern string window_title;
extern string "BASE";
extern string [SJIS]"Does_not_support_D3DFMT_A8R8G8B8,_works_in_color_reduction_mode\n";
extern string [SJIS]"Video_card_does_not_support_async_flip,_can't_work_with_Force60Frame\n";
extern string [SJIS]"Does_not_support_D3DTEXOPCAPS_ADD,_works_in_color_addition_emulate_mode\n";
extern string [SJIS]"Works_with_T&L_HAL\n";
extern string [SJIS]"Works_with_HAL\n";
extern string [SJIS]"It_works_with_REF,_but_it's_too_heavy_to_be_a_game...\n";
extern string [SJIS]"Direct3D_initialization_failed,_the_game_cannot_be_played_with_this\n";
extern string [SJIS]"Try_to_make_the_back_buffer_unlockable\n";
extern string [SJIS]"The_refresh_rate_cannot_be_changed,_vsync_changes_to_async\n";
extern string [SJIS]"HAL_doesn't_seem_to_work_either\n";
extern string [SJIS]"T&L_HAL_doesn't_seem_to_work\n";
extern string [SJIS]"Change_the_refresh_rate_to_60Hz\n";
extern string [SJIS]"Initial_startup,_screen_initialized_with_16Bits";
extern string [SJIS]"Initial_startup,_screen_initialized_with_32Bits\n";
extern string [SJIS]"Two_cannot_be_started\n";
extern string "Touhou_Koumakyou_App";
extern string log.txt;
extern string "./log.txt";
extern string writeText;
extern pointer lpCaption_0046b520;
extern pointer "log";
extern string "----------------------------------------------------------_\n";
extern cls_0x46b564::vftable_46b564 __UnknownD_FuncPtr;
extern cls_0x46b568::vftable_46b568 __UnknownE_FuncPtr;
extern string [SJIS]"error_:_MIDI_File_cannot_be_read_%s_\n";
extern string [SJIS]:"error_:_Trying_to_play_even_though_MIDI_is_not_loaded_yet\n";
extern string "error_:\n";
extern string [SJIS]"KoumakyoMD.dat";
extern string errString;
extern string [SJIS]"error_:_Failed_to_initialize_characters\n";
extern string "data/text.anm";
extern string "data/title/th06logo.jpg";
extern string [SJIS]"KoumakyoIN.dat";
extern string [SJIS]"I_found_a_valid_pad\n";
extern string [SJIS]"DirectInput_has_been_successfully_initialized\n";
extern string [SJIS]"DirectInput_SetCooperativeLevel_cannot_be_used\n";
extern string [SJIS]"DirectInput_SetDataFormat_cannot_be_used\n";
extern string [SJIS]"DirectInput_is_not_available\n";
extern float 512.0f;
extern float 0.6f;
extern float 0.8f;
extern float 0.7f;
extern float 0.9f;
extern string "%.02ffps";
extern float 1000.0f;
extern float 0.99f;
extern string [SJIS]"error_:_The_data_version_is_different\n";
extern string "ver%.4x.dat";
extern string "%s_open_...\n";
extern string [SJIS]"Is_the_folder_write-protected_or_is_the_disk_full?\n";
extern string [SJIS]"Unable_to_export_file_%s\n";
extern string [SJIS]"Do_not_use_DirectInput_for_pad_and_keyboard_input\n";
extern string [SJIS]"Force_reference_rasterizer\n";
extern string [SJIS]"Start_in_window_mode\n";
extern string [SJIS]"Suppresses_texture_color_composition_n";
extern string [SJIS]"Set_to_60_frame_forced_mode\n";
extern string [SJIS]"Suppress_depth_test\n";
extern string [SJIS]"Suppresses_Gouraud_shading\n";
extern string [SJIS]"Suppress_the_drawing_of_items_around_the_game\n";
extern string [SJIS]"Forces_the_back_buffer_to_clear\n";
extern string [SJIS]"Force_the_use_of_16-bit_textures\n";
extern string [SJIS]"Suppress_the_use_of_fog\n";
extern string [SJIS]"Suppress_the_use_of_vertex_buffers\n";
extern string [SJIS]"The_config_data_was_corrupted,_so_I_reinitialized_it.\n";
extern string [SJIS]"Initialized_because_the_config_data_cannot_be_found\n";
extern string [SJIS]"Since_there_is_no_wave_data,_set_it_to_midi\n";
extern string "bgm/th06_01.wav";
extern float 248.0f;
extern string "%2d.";
extern float 93.0f;
extern string "data/musiccmt.txt";
extern string "data/music02.anm";
extern string "data/music01.anm";
extern string "data/music00.anm";
extern string "data/result/music.jpg";
extern float 1/3_f;
extern string "data/player01.anm";
extern string "data/player00.anm";
extern string magic_T6RP;
extern string "error_:_replay.cpp";
extern string "NO_NAME";
extern string "Replay_Size_%d\n";
extern float 2.34f;
extern float 1.12f;
extern string "%s_write_...\n";
extern string [SJIS]"Rin_Saetsuki_[Wind]";
extern string [SJIS]"Rin_Saetsuki_[flower]";
extern string [SJIS]"Marisa_Kirisame_[love]";
extern string [SJIS]"Marisa_Kirisame_[Magic]";
extern string [SJIS]"Reimu_Hakurei_[Dream]";
extern string [SJIS]"Reimu_Hakurei_[spirit]";
extern string [Keyboard];
extern string "________";
extern string "HSCR";
extern string "./replay/th6_%.2d.rpy";
extern string "replay";
extern string "Extra";
extern string "Lunatic";
extern string "Hard";
extern string "Normal";
extern string "Easy";
extern float 0.0025f;
extern float 50.0f;
extern string "______100%%";
extern float 70.0f;
extern string "____%3.2f%%";
extern Alignment __UnknownF_FloatTable;
extern float 22.0f;
extern float 198000000.0f;
extern pointer g_currentDrawPtr;
extern pointer "%9d";
extern float 39600.0f;
extern float 89500.0f;
extern string "counat_=_%d\n";
extern string [SJIS]"?????";
extern float -4.0f;
extern string "MarisaB";
extern string "MarisaA";
extern string "ReimuB_";
extern string "ReimuA_";
extern string "No.%.2d_--------_--/--/--_-------_________0";
extern string "%8s";
extern string "No.%.2d_%8s_%8s_%7s_%9d";
extern string "No.___Name_____Date_____Player_Score";
extern float 1.2f;
extern float 356.0f;
extern string "%3d/%3d";
extern string "No.%.2d";
extern float 336.0f;
extern string g_%8s;
extern string "%8s";
extern float 300.0f;
extern string "%8s_%9d[C]";
extern string "%8s_%9d[1]";
extern string "%8s_%9d[%d]";
extern float 36.0f;
extern pointer "%2d";
extern string "___%8s";
extern string "____";
extern float 18.0f;
extern string "Nanashi_";
extern string "DMYS";
extern string "data/result03.anm";
extern string "data/result02.anm";
extern string "data/result01.anm";
extern string "data/result00.anm";
extern string "data/result/result.jpg";
extern string "data/wav/powerup.wav";
extern string "data/wav/graze.wav";
extern string "data/wav/timeout.wav";
extern string "data/wav/extend.wav";
extern string "data/wav/kira02.wav";
extern string "data/wav/kira01.wav";
extern string "data/wav/kira00.wav";
extern string "data/wav/item00.wav";
extern string "data/wav/damage00.wav";
extern string "data/wav/nep00.wav";
extern string "data/wav/enep01.wav";
extern string "data/wav/lazer01.wav";
extern string "data/wav/lazer00.wav";
extern string "data/wav/cat00.wav";
extern string "data/wav/gun00.wav";
extern string "data/wav/select00.wav";
extern string "data/wav/cancel00.wav";
extern string "data/wav/ok00.wav";
extern string "data/wav/tan02.wav";
extern string "data/wav/tan01.wav";
extern string "data/wav/tan00.wav";
extern string "data/wav/power1.wav";
extern string "data/wav/power0.wav";
extern string "data/wav/pldead00.wav";
extern string "data/wav/enep00.wav";
extern string "data/wav/plst00.wav";
extern string [SJIS]"DirectSound_has_been_successfully_initialized\n";
extern string [SJIS]"DirectSound_object_initialization_failed\n";
extern string "data";
extern string "fmt";
extern string [SJIS]"Isn't_it_a_Wav_file?_%s\n";
extern string "WAVE";
extern string [SJIS]"Not_a_Wav_file_%s\n";
extern string "RIFF";
extern string "comp\n";
extern string [SJIS]"error_:_Could_not_create_sound_buffer_for_streaming\n";
extern string "error_:_wav_file_load_error_%s\n";
extern string "load_BGM\n";
extern string "play_BGM\n";
extern string "stop_BGM\n";
extern string "stop_m_dwNotifyThreadID\n";
extern string [SJIS]"error_:_Sound_file_cannot_read_Check_data_%s\n";
extern undefined4 D3DFMT_R5G6B5;
extern undefined4 D3DFMT_A4R4G4B4;
extern string [SJIS]"error_:_Image_does_not_have_ƒ¿\n";
extern string [SJIS]"Texture_%s_cannot_be_loaded._Data_is_lost_or_corrupted\n";
extern string [SJIS]"Sprite_animation_%s_cannot_be_loaded._Data_is_lost_or_corrupted\n";
extern float 0.5f;
extern double 0.0d;
extern string [SJIS]"%s_cannot_be_read.\n";
extern string "Reflesh_Rate_=_%f\n";
extern float 6/7_f;
extern float 68.0f;
extern float 73.5f;
extern float 77.5f;
extern float 0.7058824f;
extern float 82.5f;
extern float 2/3_f;
extern float 87.5f;
extern float 95.0f;
extern float 110.0f;
extern float 0.4f;
extern float 135.0f;
extern float 3/8_f;
extern float 155.0f;
extern float -6.0f;
extern string [SJIS]"Failed_to_load_the_select_screen\n";
extern string "data/demo/demo00.rpy";
extern string "bgm/th06_01.mid";
extern string "../";
extern string "User_";
extern string "./replay/%s";
extern string "th6_ud????.rpy";
extern string "./replay";
extern string "Extra_";
extern string "Stage6";
extern string "Stage5";
extern string "Stage4";
extern string "Stage3";
extern string "Stage2";
extern string "Stage1";
extern string "Extra__";
extern string "Lunatic";
extern string "Hard___";
extern string "Normal_";
extern string "Easy___";
extern string "%s_---------";
extern string "%s_%9d";
extern string "Stage__LastScore";
extern string "_______%2.3f%%";
extern string "%s_%8s__%8s_%7s__%7s";
extern string "No.___Name______Date_____Player___Rank";
extern string "STAGE_%d__%.9d";
extern string "data/title/title00.jpg";
extern string "data/title04s.anm";
extern string "data/title01s.anm";
extern string "data/title04.anm";
extern string "data/title03.anm";
extern string "data/title02.anm";
extern string "data/title01.anm";
extern string [SJIS]"KoumakyoTL.dat";
extern string "data/slpl01b.anm";
extern string "data/slpl01a.anm";
extern string "data/slpl00b.anm";
extern string "data/slpl00a.anm";
extern string "data/select05.anm";
extern string "data/select04.anm";
extern string "data/select03.anm";
extern string "data/select02.anm";
extern string "data/select01.anm";
extern string "data/title/select00.jpg";
extern string "data/replay00.anm";
extern string [SJIS]"Debug_:_title_Start_VRAM_=_%d\n";
extern cls_0x46c680::vftable_46c680 __UnknownH_FuncPtr;
extern string "\n";
extern string "%d_";
extern string "CSound::Stop_";
extern cls_0x46c69c::vftable_46c69c __UnknownI_FuncPtr;
extern string "error_:_m_apDSBuffer[0]_in_HandleWaveStreamNotification\n";
extern string "error_:_m_pWaveFile->Read[+]_in_HandleWaveStreamNotification\n";
extern string "error_:_m_pWaveFile->ResetFile_in_HandleWaveStreamNotification\n";
extern string "error_:_m_pWaveFile->Read_in_HandleWaveStreamNotification\n";
extern string "error_:_Buffer->Lock_in_HandleWaveStreamNotification\n";
extern string "error_:_FillBufferWithSound_in_HandleWaveStreamNotification\n";
extern string "error_:_RestoreBuffer_in_HandleWaveStreamNotification\n";
extern string "error_:_ResetFile_in_CWaveFile::Open\n";
extern string "error_:_ReadOpen_in_CWaveFile::Open\n";
extern string "error_:_mmioOpen_in_CWaveFile::Open\n";
extern string "too_Meny_Open_Files_\n";
extern string "The_file_is_being_used_by_another_application_and_is_unavailable._\n";
extern string "The_directory_specification_is_incorrect._\n";
extern string "Another_failure_condition_occurred._This_is_the_default_error_for_an_open-file_failure._\n";
extern string "The_file_is_protected_and_cannot_be_opened._\n";
extern string "error_:_mmioSetInfo_in_CWaveFile::ResetFile\n";
extern string "error_:_mmioinfo.In.pchNext_==_mmioinfoIn.pchEndRead_in_CWaveFile::ResetFile\n";
extern string "error_:_mmioAdvance_in_CWaveFile::ResetFile\n";
extern string "error_:_mmioGetInfo_in_CWaveFile::ResetFile\n";
extern string "error_:_mmioDescend_in_CWaveFile::ResetFile\n";
extern string "error_:_mmioSeek_in_CWaveFile::ResetFile\n";
extern string "error_:_m_hmmio\t==_NULL_in_CWaveFile::ResetFile\n";
extern string "error_:\t%s[%s]\n";
extern string "zwave.cpp";
extern cls_0x46cb7c::vftable_46cb7c __UnknownJ_FuncPtrTable;
extern cls_0x46cb9c::vftable_46cb9c __UnknownK_FuncPtrTable;
extern cls_0x46cbbc::vftable_46cbbc __UnknownL_FuncPtrTable;
extern cls_0x46cbe8::vftable_46cbe8 __UnknownN_FuncPtrTable;
extern cls_0x46d034::vftable_46d034 __UnknownO_FuncPtrTable;
extern cls_0x46d058::vftable_46d058 __UnknownP_FuncPtrTable;
extern Alignment -0.5f;
extern Alignment 0.5d;
extern string "1.0.5";
extern undefined4 __GUID_A;
extern undefined4 __GUID_B;
extern cls_0x46d0e8::vftable_46d0e8 __UnknownQ_FuncPtrTable;
extern cls_0x46d134::vftable_46d134 __UnknownR_FuncPtrTable;
extern cls_0x46d174::vftable_46d174 __UnknownS_FuncPtrTable;
extern undefined * __UnknownT_FuncPtrTable;
extern undefined * __UnknownU_FuncPtrTable;
extern undefined * __UnknownV_FuncPtrTable;
extern undefined * __UnknownW_FuncPtrTable;
extern undefined * __UnknownX_FuncPtrTable;
extern undefined * __UnknownY_FuncPtrTable;
extern undefined * __UnknownZ_FuncPtrTable;
extern undefined * __UnknownAA_FuncPtrTable;
extern undefined * __UnknownAB_FuncPtrTable;
extern undefined * __UnknownAC_FuncPtrTable;
extern undefined * __UnknownAD_FuncPtrTable;
extern undefined * __UnknownAE_FuncPtrTable;
extern undefined * __UnknownAF_FuncPtrTable;
extern undefined * __UnknownAG_FuncPtrTable;
extern undefined * __UnknownAH_FuncPtrTable;
extern undefined * __UnknownAI_FuncPtrTable;
extern undefined * __UnknownAJ_FuncPtrTable;
extern undefined * __UnknownAK_FuncPtrTable;
extern undefined * __UnknownAL_FuncPtrTable;
extern undefined * __UnknownAM_FuncPtrTable;
extern undefined * __UnknownAN_FuncPtrTable;
extern undefined * __UnknownAO_FuncPtrTable;
extern cls_0x46d288::vftable_46d288 __UnknownAP_FuncPtrTable;
extern cls_0x46d294::vftable_46d294 __UnknownAQ_FuncPtrTable;
extern undefined * PTR_error_messages;
extern undefined * __JPEGLibraryCrap_StringPtrTable;
extern string "invalid_bit_length_repeat";
extern string "too_many_length_or_distance_symbols";
extern string "invalid_stored_block_lengths";
extern string "invalid_block_type";
extern string "invalid_literal/length_code";
extern string "incomplete_dynamic_bit_lengths_tree";
extern string "oversubscribed_dynamic_bit_lengths_tree";
extern string "incomplete_literal/length_tree";
extern string "oversubscribed_literal/length_tree";
extern string "empty_distance_tree_with_lengths";
extern string "incomplete_distance_tree";
extern string "oversubscribed_distance_tree";
extern string "CorExitProcess";
extern string "mscoree.dll";
extern string "e+000";
extern string "[null]";
extern string "Microsoft_Visual_C++_Runtime_Library";
extern string "Program:_";
extern string "<program_name_unknown>";
extern string "A_buffer_overrun_has_been_detected_which_has_corrupted_the_program's\ninternal_state.__The_program_cannot_safely_continue_execution_and_must\nnow_be_terminated.\n";
extern string "Buffer_overrun_detected!";
extern string "A_security_error_of_unknown_cause_has_been_detected_which_has\ncorrupted_the_program's_internal_state.__The_program_cannot_safely\ncontinue_execution_and_must_now_be_terminated.\n";
extern string "Unknown_security_failure_detected!";
extern string "modf";
extern string "floor";
extern string "ceil";
extern string "atan";
extern string "log10";
extern string "pow";
extern string "exp10";
extern LPCWSTR lpSrcStr_00474884;
extern LPCWSTR 0.0f;
extern AsciiManager ascii_manager;
extern UpdateFunc ASCII_MANAGER_ON_TICK;
extern UpdateFunc ascii_manager_on_tick;
extern UpdateFunc STAGE_ON_DRAW_03;
extern UpdateFunc stage_on_draw;
extern Stage Stage;
extern UpdateFunc STAGE_ON_DRAW_04;
extern UpdateFunc stage_on_draw_b;
extern UpdateFunc STAGE_ON_TICK;
extern UpdateFunc stage_on_tick;
extern EnemyManager enemy_manager;
extern UpdateFunc enemy_manager_on_tick;
extern UpdateFunc bullet_manager_on_draw;
extern BulletManager bullet_manager;
extern UpdateFunc bullet_manager_on_tick;
extern Gui gui;
extern UpdateFunc GUI_ON_DRAW-{priority};
extern UpdateFunc GUI_ON_TICK-{priority};
extern GameManager game_manager;
extern UpdateFunc game_manager_on_tick;
extern UpdateFunc GAME_MANAGER_ON_TICK-{priority};
extern UpdateFunc game_manager_on_draw;
extern JOYCAPSA joypad_caps;
extern JOYCAPSA JOYPAD_CAPS-{wMid};
extern Rng Rng;
extern Input input;
extern UpdateFuncRegistry UpdateFuncRegistry;
extern UpdateFuncRegistry update_func_registry;
extern LogBuffer LogBuffer;
extern ItemManager item_manager;
extern Window g_windowHandle;
extern Window Window;
extern Supervisor Supervisor;
extern Supervisor supervisor;
extern Player g_player;
extern Player player;
extern SoundManager sound_manager;
extern AnmManager * g_AnmManager;
extern AnmManager * anm_manager_ptr;
extern IconResource Rsrc_Icon_1_411;
extern GroupIconResource Rsrc_GroupIcon_69_411;
extern void *32 ExceptionList;
extern void *32 StackBase;
extern void *32 StackLimit;
extern void *32 SubSystemTib;
extern void *32 FiberData;
extern void *32 ArbitraryUserPointer;
extern void *32 Self;
extern void *32 EnvironmentPointer;
extern CLIENT_ID ClientId;
extern void *32 ActiveRpcHandle;
extern void *32 ThreadLocalStoragePointer;
extern void *32 ProcessEnvironmentBlock;
extern dword LastErrorValue;
extern dword CountOfOwnedCriticalSections;
extern void *32 CsrClientThread;
extern void *32 Win32ThreadInfo;
extern dword[26] User32Reserved;
extern dword[5] UserReserved;
extern void *32 WOW32Reserved;
extern dword CurrentLocale;
extern dword FpSoftwareStatusRegister;
extern void *32[54] SystemReserved1;
extern dword ExceptionCode;
extern void *32 ActivationContextStackPointer;
extern uchar[36] SpareBytes;
extern dword TxFsContext;
extern dword GdiTebBatch;
extern CLIENT_ID RealClientId;
extern void *32 GdiCachedProcessHandle;
extern dword GdiClientPID;
extern dword GdiCLientTID;
extern void *32 GdiThreadLocalInfo;
extern void *32[62] Win32ClientInfo;
extern void *32[233] glDispatchTable;
extern void *32[29] glReserved1;
extern void *32 glReserved2;
extern void *32 glSectionInfo;
extern void *32 glSection;
extern void *32 glTable;
extern void *32 glCurrentRC;
extern void *32 glContext;
extern dword LastStatusValue;
extern wchar16[261] StaticUnicodeBuffer;
extern void *32 DeallocationStack;
extern void *32[64] TlsSlots;
extern void *32 TlsLinks.Flink;
extern void *32 TlsLinks.Blink;
extern void *32 Vdm;
extern void *32 ReservedForNtRpc;
extern void *32[2] DbgSsReserved;
extern dword HardErrorMode;
extern void *32[9] Instrumentation;
extern GUID ActivityId;
extern void *32 SubProcessTag;
extern void *32 EtwLocalData;
extern void *32 EtwTraceData;
extern void *32 WinSockData;
extern dword GdiBatchCount;
extern dword IdealProcessorValue;
extern dword GuaranteedStackBytes;
extern void *32 ReservedForPerf;
extern void *32 ReservedForOle;
extern dword WaitingOnLoaderLock;
extern void *32 SavedPriorityState;
extern void *32 SoftPatchPtr1;
extern void *32 ThreadPoolData;
extern void *32 TlsExpansionSlots;
extern dword MuiGeneration;
extern dword IsImpersonating;
extern void *32 NlsCache;
extern void *32 pShimData;
extern dword HeapVirtualAffinity;
extern void *32 CurrentTransactionHandle;
extern void *32 ActiveFrame;
extern void *32 FlsData;
extern void *32 PreferredLanguages;
extern void *32 UserPrefLanguages;
extern void *32 MergedPrefLanguages;
extern dword MuiImpersonation;
extern ushort CrossTebFlags;
extern ushort SameTebFlags;
extern void *32 TxnScopeEnterCallback;
extern void *32 TxnScopeExitCallback;
extern void *32 TxnScopeContext;
extern dword LockCount;
extern void *32 ResourceRetValue;

#endif // GLOBAL_VARIABLES_H
